#!/usr/bin/env bash
set -e

echo "Version: $VERSION"

dotnet test --no-build --configuration Release --verbosity normal \
  --logger "trx;LogFileName=tests.trx" --logger "console;verbosity=detailed" \
  /p:CollectCoverage=true /p:Include="[NContract]*" /p:Threshold=100 src/NContract.sln
